#!/bin/sh

# Monitors
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Layout
bspc config window_gap 16
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config padding 0

# Window placement
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config removal_adjustment true

# Pointer behavior
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config pointer_motion_interval 7
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Window rules
bspc rule -a Navigator desktop=1 follow=on
bspc rule -a Thunar desktop=focused state=floating
bspc rule -a mpv desktop=focused state=fullscreen

# Remove cache
rm -fr $HOME/.cache/eww/
rm -fr $HOME/.cache/fish/
rm -fr $HOME/.cache/fontconfig/

# Cursor options
xset m 0 0 # disable mouse acceleration
xrdb ~/.Xresources
xsetroot -cursor_name left_ptr &

# Set the background
hsetroot -fill "$HOME/.config/bspwm/imgs/background.png" &

# Autostart widgets
pgrep -f 'eww --config .* daemon' >/dev/null || eww --config "$HOME/.config/eww/" daemon &
pgrep -f 'eww --config .* open bar' >/dev/null || eww --config "$HOME/.config/eww/" open bar
pgrep -f 'eww --config .* open license' >/dev/null || eww --config "$HOME/.config/eww/" open license

# Autostart hotkey daemon
pgrep -x sxhkd >/dev/null || sxhkd &

# Autostart compositor
pkill picom >/dev/null 2>&1
picom --config "$HOME/.config/picom/picom.conf" &

# Low battery alert
pgrep -f 'bin/alert' >/dev/null || ./bin/alert &

# Clipboard manager
pgrep -f 'xclip.*clipboard.txt' >/dev/null || (
  while true; do
    xclip -o -selection clipboard > ~/.cache/clipboard.txt 2>/dev/null
    sleep 0.5
  done
) &
